name: production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Reset database
        run: heroku pg:reset --app=${{ secrets.PRODUCTION_APP_NAME }} --confirm=${{ secrets.PRODUCTION_APP_NAME }}

      - name: Log in to Heroku Container Registry
        run: heroku container:login

      - name: Build and push
        run: heroku container:push -a ${{ secrets.PRODUCTION_APP_NAME }} web

      - name: Release the image
        run: heroku container:release -a ${{ secrets.PRODUCTION_APP_NAME }} web

      - name: Migrate the database
        run: heroku run -a ${{ secrets.PRODUCTION_APP_NAME }} sequelize db:migrate

      - name: Seed the database
        run: heroku run -a ${{ secrets.PRODUCTION_APP_NAME }} sequelize db:seed:all
