name: staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Reset database
        run: heroku pg:reset --app=${{ secrets.STAGING_APP_NAME }} --confirm=${{ secrets.STAGING_APP_NAME }}

      - name: Log in to Heroku Container Registry
        run: heroku container:login

      - name: Build and push
        run: heroku container:push -a ${{ secrets.STAGING_APP_NAME }} web

      - name: Release the image
        run: heroku container:release -a ${{ secrets.STAGING_APP_NAME }} web

      - name: Build assets
        run: heroku run -a ${{ secrets.STAGING_APP_NAME }} yarn run build-assets

      - name: Migrate the database
        run: heroku run -a ${{ secrets.STAGING_APP_NAME }} sequelize db:migrate

      - name: Seed the database
        run: heroku run -a ${{ secrets.STAGING_APP_NAME }} sequelize db:seed:all
